### ISSUE TITLE
View paper details

### ISSUE THREAD

**Issue by MatMoore** [COVID-science-engine/crowdsourced-papers-frontend#23]
**Is your feature request related to a problem? Please describe.**
As a researcher visiting CSE I want to see the papers relevant for my specific project so I can so I can chose which papers to download.

Currently we have a listing of papers but there isn't a page where you can view all the details for a paper including a summary of the methods and data. Clicking on the paper takes you directly to the journal.

**Describe the solution you'd like**
When you click a link from the listing page, you should be able to go to a details page that contains all the information we've collected about it, including the link to the article itself.

The listing page should only contain the basic information required to understand whether the paper is relevant to the user.

[Prototype v5 wireframes](https://www.figma.com/file/RtHSp2qSI9TJfzxjRmLCOj/Covid-Science-Engine---Design-System?node-id=95%3A727)
![Prototype V5 0 1 - Paper Page](https://user-images.githubusercontent.com/87579/79429932-18846680-7fc0-11ea-9431-17ea3b8cf639.png)
![Prototype V 5 1 - Compact Article Cards with tags](https://user-images.githubusercontent.com/87579/79430005-3225ae00-7fc0-11ea-8b69-234fc7deca06.png)

**Describe alternatives you've considered**
We think including all this info on the listings page would be too dense. 

**Additional context**
https://docs.google.com/document/d/1CT06S0b6KvHmLl06i5CAFwRJWvJiwJXy6WuQFcSeuiU/edit

**Comment by herrherrmann** [comment]
Shit, I mis-clicked.

**Comment by herrherrmann** [comment]
Would be happy to take this one! (I could start work on it on the weekend.)
