### ISSUE TITLE
Add navigation button group component

### ISSUE THREAD

**Issue by MatMoore** [COVID-science-engine/crowdsourced-papers-frontend#43]
**Is your feature request related to a problem? Please describe.**
In https://github.com/COVID-science-engine/crowdsourced-papers-frontend/pull/33 I added some more buttons to the nav bar, but they aren't styled yet so it's just a bunch of buttons stacked on top of each other.

**Describe the solution you'd like**
I think we should add a component to capture the nav bar.

**Describe alternatives you've considered**
None

**Additional context**
This is what it looks like in the designs:
![Screen Shot 2020-05-02 at 15 53 21](https://user-images.githubusercontent.com/87579/80867639-28bd6680-8c8d-11ea-86d6-3bfac9b9efc1.png)

**Comment by herrherrmann** [comment]
Like in the Footer, you could use buttons with `color="transparent"` – they'll look very similar to the specified design. But yes, we probably still need to adjust the wrapper element to position them properly.
